### ISSUE TITLE
How do you find the number to set for the st_set_crs

### ISSUE THREAD

**Issue by aef1004** [aef1004/R_Hw_5#4]
You have to set the st_set_crs() when doing st_as_sf.  I'm not sure how to find the actual number, so I picked an arbitrary one so that it will work.

homicides_sf <- st_as_sf(Houston_homicides,
                         coords = c("lon", "lat")) %>%
  st_set_crs(4326)

**Comment by randyxun** [comment]
Well 4326 is not arbitrary. It's the designation for the American coordinate system. 3347 is for the Canadian system, which is basically the same except in meters.
